apiVersion: v1
kind: Pod
metadata:
  name: hello-server
  labels: 
    app: hello-server
spec:
  containers:
  - name: hello-server
    image: blux2/hello-server:1.0
    ports:
    - containerPort: 8080
