apiVersion: v1
kind: Pod
metadata:
  name: hello-server-custom
  labels: 
    app: hello-server-custom
spec:
  imagePullSecrets:
  - name: regcred     # ← 作成した Secret 名を指定
  containers:
  - name: hello-server-custom
    image: manabujahana/chapter01:1.0.0
    ports:
    - containerPort: 8080
