apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJtYW5hYnVqYWhhbmEiLCJwYXNzd29yZCI6ImRja3JfcGF0X1lEeFlnS1QyTko2MjJSNUpsenBVYTNKRkZ2ZyIsImVtYWlsIjoibWFuYWJ1LmphaGFuYUBnbWFpbC5jb20iLCJhdXRoIjoiYldGdVlXSjFhbUZvWVc1aE9tUmphM0pmY0dGMFgxbEVlRmxuUzFReVRrbzJNakpTTlVwc2VuQlZZVE5LUmtaMlp3PT0ifX19
kind: Secret
metadata:
  name: regcred
  namespace: dev
type: kubernetes.io/dockerconfigjson
