apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: dev
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJtYW5hYnVqYWhhbmEiLCJwYXNzd29yZCI6ImRja3JfcGF0X1JWeHJ1Z2xXczZVWkFVb3Z3c0FIUGZfMkJ4USIsImVtYWlsIjoibWFuYWJ1LmphaGFuYUBnbWFpbC5jb20iLCJhdXRoIjoiYldGdVlXSjFhbUZvWVc1aE9tUmphM0pmY0dGMFgxSldlSEoxWjJ4WGN6WlZXa0ZWYjNaM2MwRklVR1pmTWtKNFVRPT0ifX19
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: dev
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpassword"
  MYSQL_PASSWORD: "Mj19770126"