apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

# 既存のリソースファイルを指定
resources:
  - 00-configmap.yaml
  - 01-mysql.yaml
  - 02-web-php.yaml
  - 03-ingress.yaml
  - 04-migration-job.yaml

# イメージ名とタグの一括管理
images:
  - name: app-image
    newName: manabujahana/training-sample
    newTag: 1.0.2

# Secret の自動生成定義
secretGenerator:
  # 1. DB用 Secret (app-secrets)
  - name: app-secrets
    envs:
      - .env.secret
    type: Opaque

  # 2. Docker Registry用 Secret（dockerconfigjson）
  - name: regcred
    files:
      - .dockerconfigjson=config.json
    type: kubernetes.io/dockerconfigjson

  # 3. Ingress 用 TLS 認証用 Secret (tls-seret)
  - name: tls-secret
    files:
      - tls.crt
      - tls.key
    type: kubernetes.io/tls
