apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-server
  labels:
    app: hello-server
spec:
  replicas: 3             # ← ReplicaSet に Pod を 3つ管理するよう指示
  selector:
    matchLabels:
      app: hello-server   # ← template の labels と一致している必要がある
  template:
    metadata:
      labels:
        app: hello-server
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: hello-server
        image: manabujahana/chapter01:1.0.0
        #env:
        #- name: TRIGGER_UPDATE
        #  value: "v2"
        ports:
        - containerPort: 80