apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: laravel-k8s-dev
build:
  artifacts:
    - image: manabujahana/training-sample # お使いの Docker イメージ名
      context: .
      docker:
        dockerfile: docker/Dockerfile
        buildArgs:
          APP_DIR: "bookman"    # Skaffold が Docker Image を build する際の APP_DIR を指定
      sync:
        manual:
          # bookman ディレクトリ配下の変更をコンテナ内の /var/www/html へ直接同期
          - src: 'bookman/**/*.php'
            dest: /var/www/html
          - src: 'bookman/**/*.blade.php'
            dest: /var/www/html
          - src: 'bookman/**/*.css'
            dest: /var/www/html
          - src: 'bookman/**/*.js'
            dest: /var/www/html
          - src: 'bookman/**/*.json'
            dest: /var/www/html
          # ビルド後の public 配下も同期対象に含める
          - src: 'bookman/public/**/*'
            dest: /var/www/html
manifests:
  kustomize:
    paths:
    - manifest/               # k8s ディレクトリ配下のマニフェストファイル群（環境に合わせて調整）
portForward:
  - resourceType: Service
    resourceName: web-php-service
    namespace: dev
    port: 80
    localPort: 8080

