apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: laravel-k8s-dev
build:
  artifacts:
    - image: manabujahana/training-sample # お使いの Docker イメージ名
      context: .
      docker:
        dockerfile: docker/Dockerfile
      sync:
        infer:
          - "**/*.php"        # PHP ファイルの変更を検知して Pod 内に自動同期
          - "**/*.blade.php"
          - "**/*.css"
          - "**/*.js"
          - "**/*.json"
      buildArgs:
        APP_DIR: "bookman"    # Skaffold が Docker Image を build する際の APP_DIR を指定
manifests:
  kustomize:
    paths:
    - manifest/               # k8s ディレクトリ配下のマニフェストファイル群（環境に合わせて調整）
portForward:
  - resourceType: Service
    resourceName: web-php-service
    namespace: dev
    port: 80
    localPort: 8080

