apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJtYW5hYnVqYWhhbmEiLCJwYXNzd29yZCI6ImRja3JfcGF0X0VhTGR5VnQ1TEpXMUx1RmI5ckdMSHdWQjV0YyIsImVtYWlsIjoibWFuYWJ1LmphaGFuYUBnbWFpbC5jb20iLCJhdXRoIjoiYldGdVlXSjFhbUZvWVc1aE9tUmphM0pmY0dGMFgwVmhUR1I1Vm5RMVRFcFhNVXgxUm1JNWNrZE1TSGRXUWpWMFl3PT0ifX19
kind: Secret
metadata:
  name: regcred
  namespace: dev
type: kubernetes.io/dockerconfigjson
